language: python
python:
  - "2.6"
  - "2.7"
  - "3.4"
# command to install dependencies
install:
  - pip install -r test_requirements.txt
# command to run tests
script:
  - pytest
  - pycodestyle fortls --max-line-length=120 --ignore=E226,E722
  - pyflakes fortls
