name: "Docs"
on: [push, pull_request]

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: sphinx-toolbox/sphinx-action@master
        with:
          pre-build-command: "pip install .[docs]"
          docs-folder: "docs/"
      - name: Set fortran-lang domain
        if: github.ref == 'refs/heads/master'
        run: |
          echo fortls.fortran-lang.org > CNAME
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/master'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/_build/html
